(function (global) {
  "use strict";

  // Static content lives outside app.js so the game logic stays focused.
  global.WORD_SEARCH_DATA = Object.freeze({
    vocabulary: Object.freeze({
      es: Object.freeze({
        animals: Object.freeze({
          label: "Animales",
          words: Object.freeze([
            "perro",
            "gato",
            "elefante",
            "jirafa",
            "león",
            "tigre",
            "cebra",
            "oso",
            "lobo",
            "conejo",
            "ciervo",
            "zorro",
            "caballo",
            "vaca",
            "oveja",
            "ardilla",
            "tejón",
          ]),
        }),
        fruits: Object.freeze({
          label: "Frutas",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "naranja",
            "kiwi",
            "melón",
            "uva",
            "cereza",
            "fresa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verduras",
          words: Object.freeze([
            "zanahoria",
            "patata",
            "cebolla",
            "col",
            "lechuga",
            "tomate",
            "pepino",
            "ajo",
          ]),
        }),
        colors: Object.freeze({
          label: "Colores",
          words: Object.freeze([
            "rojo",
            "azul",
            "verde",
            "amarillo",
            "naranja",
            "rosa",
            "morado",
            "blanco",
            "negro",
            "gris",
            "marrón",
            "celeste",
          ]),
        }),
        body: Object.freeze({
          label: "Cuerpo",
          words: Object.freeze([
            "cabeza",
            "mano",
            "pie",
            "brazo",
            "pierna",
            "ojo",
            "boca",
            "nariz",
            "oreja",
            "dedo",
            "rodilla",
            "espalda",
          ]),
        }),
        food: Object.freeze({
          label: "Comida",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "pan",
            "leche",
            "huevo",
            "queso",
            "arroz",
            "pasta",
            "carne",
            "pescado",
            "tomate",
          ]),
        }),
        transports: Object.freeze({
          label: "Transportes",
          words: Object.freeze([
            "coche",
            "tren",
            "barco",
            "avión",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escuela",
          words: Object.freeze([
            "lápiz",
            "goma",
            "libro",
            "mochila",
            "pizarra",
            "tijeras",
            "regla",
            "cuaderno",
            "profesora",
            "alumno",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficios",
          words: Object.freeze([
            "maestra",
            "médico",
            "cocinero",
            "pintor",
            "bombero",
            "panadero",
            "granjero",
            "cartero",
          ]),
        }),
      }),
      ca: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "gos",
            "gat",
            "elefant",
            "girafa",
            "lleó",
            "tigre",
            "zebra",
            "os",
            "llop",
            "conill",
            "cérvol",
            "guineu",
            "cavall",
            "vaca",
            "ovella",
            "esquirol",
            "teixó",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruites",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "taronja",
            "kiwi",
            "meló",
            "raim",
            "cirera",
            "maduixa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verdures",
          words: Object.freeze([
            "pastanaga",
            "patata",
            "ceba",
            "col",
            "enciam",
            "tomàquet",
            "cogombre",
            "all",
          ]),
        }),
        colors: Object.freeze({
          label: "Colors",
          words: Object.freeze([
            "vermell",
            "blau",
            "verd",
            "groc",
            "taronja",
            "rosa",
            "lila",
            "blanc",
            "negre",
            "gris",
            "marró",
            "celest",
          ]),
        }),
        body: Object.freeze({
          label: "Cos",
          words: Object.freeze([
            "cap",
            "mà",
            "peu",
            "braç",
            "cama",
            "ull",
            "boca",
            "nas",
            "orella",
            "dit",
            "genoll",
            "esquena",
          ]),
        }),
        food: Object.freeze({
          label: "Menjar",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "pa",
            "llet",
            "ou",
            "formatge",
            "arròs",
            "pasta",
            "carn",
            "peix",
            "tomàquet",
          ]),
        }),
        transports: Object.freeze({
          label: "Transports",
          words: Object.freeze([
            "cotxe",
            "tren",
            "vaixell",
            "avió",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escola",
          words: Object.freeze([
            "llapis",
            "goma",
            "llibre",
            "motxilla",
            "pissarra",
            "tisores",
            "regle",
            "quadern",
            "professora",
            "alumne",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficis",
          words: Object.freeze([
            "mestra",
            "metge",
            "cuiner",
            "pintor",
            "bomber",
            "forner",
            "pagès",
            "carter",
          ]),
        }),
      }),
      en: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "dog",
            "cat",
            "elephant",
            "giraffe",
            "lion",
            "tiger",
            "zebra",
            "bear",
            "wolf",
            "rabbit",
            "deer",
            "fox",
            "horse",
            "cow",
            "sheep",
            "squirrel",
            "badger",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruits",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "orange",
            "kiwi",
            "melon",
            "grape",
            "cherry",
            "strawberry",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Vegetables",
          words: Object.freeze([
            "carrot",
            "potato",
            "onion",
            "cabbage",
            "lettuce",
            "tomato",
            "cucumber",
            "garlic",
          ]),
        }),
        colors: Object.freeze({
          label: "Colors",
          words: Object.freeze([
            "red",
            "blue",
            "green",
            "yellow",
            "orange",
            "pink",
            "purple",
            "white",
            "black",
            "grey",
            "brown",
            "cyan",
          ]),
        }),
        body: Object.freeze({
          label: "Body",
          words: Object.freeze([
            "head",
            "hand",
            "foot",
            "arm",
            "leg",
            "eye",
            "mouth",
            "nose",
            "ear",
            "finger",
            "knee",
            "back",
          ]),
        }),
        food: Object.freeze({
          label: "Food",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "bread",
            "milk",
            "egg",
            "cheese",
            "rice",
            "pasta",
            "meat",
            "fish",
            "tomato",
          ]),
        }),
        transports: Object.freeze({
          label: "Transport",
          words: Object.freeze([
            "car",
            "train",
            "boat",
            "plane",
            "bike",
            "motorbike",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "School",
          words: Object.freeze([
            "pencil",
            "eraser",
            "book",
            "backpack",
            "board",
            "scissors",
            "ruler",
            "notebook",
            "teacher",
            "student",
          ]),
        }),
        jobs: Object.freeze({
          label: "Jobs",
          words: Object.freeze([
            "teacher",
            "doctor",
            "cook",
            "painter",
            "firefighter",
            "baker",
            "farmer",
            "postman",
          ]),
        }),
      }),
    }),
    definitions: Object.freeze({
      es: Object.freeze({
        AJO: "Bulbo blanco con sabor fuerte que se usa para cocinar.",
        ALUMNO: "Persona que aprende en la escuela.",
        AMARILLO: "Color del sol o de un plátano maduro.",
        ARDILLA: "Animal pequeño que trepa a los árboles y come frutos secos.",
        ARROZ: "Cereal pequeño y blanco que se cocina muchas veces hervido.",
        AVION: "Vehículo que vuela por el aire.",
        AZUL: "Color del cielo en un día despejado.",
        BARCO: "Vehículo que navega por el agua.",
        BICI: "Vehículo de dos ruedas que se mueve con pedales.",
        BLANCO: "Color de la nieve o del papel.",
        BOCA: "Parte del cuerpo con la que comemos y hablamos.",
        BOMBERO: "Persona que apaga incendios y ayuda en emergencias.",
        BRAZO: "Parte del cuerpo que va del hombro a la mano.",
        BUHO: "Ave nocturna con ojos grandes.",
        BUS: "Vehículo grande que transporta pasajeros.",
        CABALLO: "Animal grande que puede correr mucho y llevar personas.",
        CABEZA: "Parte del cuerpo donde están los ojos, la nariz y la boca.",
        CARNE: "Alimento que procede de animales.",
        CARTERO: "Persona que reparte cartas y paquetes.",
        CEBOLLA: "Verdura redonda con capas y sabor fuerte.",
        CEBRA: "Animal parecido al caballo con rayas blancas y negras.",
        CELESTE: "Azul muy claro, como el color del cielo.",
        CEREZA: "Fruta pequeña y redonda, normalmente roja.",
        CIERVO: "Animal de patas largas que puede tener cuernos.",
        COCHE: "Vehículo de cuatro ruedas para circular por carretera.",
        COCINERO: "Persona que prepara la comida.",
        COHETE: "Vehículo que sube al espacio.",
        COL: "Verdura de hojas apretadas y redondeadas.",
        CONEJO: "Animal pequeño con orejas largas.",
        CUADERNO: "Conjunto de hojas para escribir o dibujar.",
        DEDO: "Cada una de las partes alargadas de la mano.",
        ELEFANTE: "Animal muy grande con trompa.",
        ESPALDA: "Parte posterior del tronco.",
        ESTRELLA: "Astro que brilla con luz propia.",
        FRESA: "Fruta roja pequeña con semillas por fuera.",
        GATO: "Animal doméstico que maúlla.",
        GOMA: "Objeto que sirve para borrar lápiz.",
        GRANJERO: "Persona que trabaja en el campo o cuida animales de granja.",
        GRIS: "Color intermedio entre blanco y negro.",
        HUEVO: "Alimento con cáscara que ponen aves como la gallina.",
        JIRAFA: "Animal alto con el cuello muy largo.",
        KIWI: "Fruta pequeña de piel marrón e interior verde.",
        LAPIZ: "Herramienta para escribir o dibujar.",
        LECHE: "Líquido blanco que beben las crías de muchos mamíferos.",
        LECHUGA: "Verdura de hojas verdes que se usa mucho en ensaladas.",
        LEON: "Gran felino con melena.",
        LIBRO: "Conjunto de páginas para leer o estudiar.",
        LOBO: "Animal salvaje parecido a un perro.",
        LUNA: "Satélite que gira alrededor de la Tierra.",
        MAESTRA: "Mujer que enseña en la escuela.",
        MANO: "Parte del cuerpo con dedos para coger cosas.",
        MANZANA: "Fruta redonda que puede ser roja, verde o amarilla.",
        MARRON: "Color de la madera o del chocolate.",
        MARTE: "Planeta rojizo del sistema solar.",
        MEDICO: "Persona que cuida la salud y trata enfermedades.",
        MELON: "Fruta grande, redonda y muy refrescante.",
        METRO: "Tren urbano que circula por la ciudad, a menudo bajo tierra.",
        MOCHILA: "Bolsa con asas que se lleva a la espalda.",
        MORADO: "Color entre azul y rojo.",
        MOTO: "Vehículo de dos ruedas con motor.",
        NARANJA: "Fruta redonda y también color anaranjado.",
        NARIZ: "Parte del cuerpo con la que olemos y respiramos.",
        NEGRO: "Color de la noche sin luz.",
        OJO: "Parte del cuerpo con la que vemos.",
        ORBITA: "Camino que sigue un astro alrededor de otro.",
        OREJA: "Parte del cuerpo con la que oímos.",
        OSO: "Animal grande y fuerte del bosque.",
        OVEJA: "Animal doméstico que da lana.",
        PAN: "Alimento hecho con harina y horneado.",
        PANADERO: "Persona que hace o vende pan.",
        PASTA: "Alimento hecho con harina que se cuece en agua.",
        PATATA: "Tubérculo que crece bajo tierra.",
        PEPINO: "Verdura alargada y verde, fresca y crujiente.",
        PERA: "Fruta dulce con forma más ancha en la parte baja.",
        PERRO: "Animal doméstico que ladra.",
        PESCADO: "Alimento que se obtiene de peces u otros animales del agua.",
        PIE: "Parte del cuerpo que nos ayuda a sostenernos y caminar.",
        PIERNA: "Parte del cuerpo que va desde la cadera hasta el pie.",
        PINTOR: "Persona que pinta paredes, objetos o cuadros.",
        PIZARRA: "Superficie donde se escribe en clase.",
        PLANETA: "Astro que gira alrededor de una estrella.",
        PLATANO: "Fruta alargada y amarilla.",
        PROFESORA: "Mujer que enseña en una escuela o instituto.",
        QUESO: "Alimento que suele hacerse con leche.",
        REGLA: "Herramienta recta para medir o trazar líneas.",
        RODILLA: "Articulación que une el muslo con la pierna.",
        ROJO: "Color de la sangre o de muchas fresas.",
        ROSA: "Color suave parecido al de algunas flores.",
        SOL: "Estrella que da luz y calor a la Tierra.",
        TEJON: "Animal de bosque, robusto y de patas cortas.",
        TIGRE: "Gran felino con rayas oscuras.",
        TIJERAS: "Herramienta para cortar papel o tela.",
        TOMATE: "Fruto rojo que muchas veces se usa como verdura.",
        TREN: "Vehículo formado por vagones que va por raíles.",
        UVA: "Fruta pequeña que crece en racimos.",
        VACA: "Animal doméstico que da leche.",
        VENUS: "Planeta cercano a la Tierra.",
        VERDE: "Color de la hierba o de muchas hojas.",
        ZANAHORIA: "Verdura alargada de color naranja.",
        ZORRO: "Animal del bosque parecido a un perro, normalmente rojizo.",
      }),
      ca: Object.freeze({
        ALL: "Bulb blanc amb gust fort que es fa servir per cuinar.",
        ALUMNE: "Persona que aprèn a l'escola.",
        ARROS: "Cereal petit i blanc que sovint es cuina bullit.",
        AVIO: "Vehicle que vola per l'aire.",
        BICI: "Vehicle de dues rodes que es mou amb pedals.",
        BLANC: "Color de la neu o del paper.",
        BLAU: "Color del cel en un dia clar.",
        BOCA: "Part del cos amb què mengem i parlem.",
        BOMBER: "Persona que apaga incendis i ajuda en emergències.",
        BRAC: "Part del cos que va de l'espatlla a la mà.",
        BUS: "Vehicle gran que transporta passatgers.",
        CAMA: "Part del cos que ens ajuda a caminar.",
        CAP: "Part del cos on hi ha els ulls, el nas i la boca.",
        CARN: "Aliment que prové d'animals.",
        CARTER: "Persona que reparteix cartes i paquets.",
        CAVALL: "Animal gran que pot córrer molt i portar persones.",
        CEBA: "Verdura rodona amb capes i gust fort.",
        CELEST: "Blau molt clar, com el color del cel.",
        CERVOL: "Animal de potes llargues que pot tenir banyes.",
        CIRERA: "Fruita petita, rodona i sovint vermella.",
        COET: "Vehicle que puja a l'espai.",
        COGOMBRE: "Verdura allargada i verda, fresca i cruixent.",
        COL: "Verdura de fulles apretades i forma rodona.",
        CONILL: "Animal petit amb orelles llargues.",
        COTXE: "Vehicle de quatre rodes per anar per carretera.",
        CUINER: "Persona que prepara el menjar.",
        DIT: "Cadascuna de les parts llargues de la mà.",
        ELEFANT: "Animal molt gran amb trompa.",
        ENCIAM: "Verdura de fulles verdes que es menja en amanides.",
        ESQUENA: "Part posterior del tronc.",
        ESQUIROL: "Animal petit que s'enfila als arbres i menja fruits secs.",
        ESTRELLA: "Astre que fa llum al cel.",
        FORMATGE: "Aliment que normalment es fa amb llet.",
        FORNER: "Persona que fa o ven pa.",
        GAT: "Animal domèstic que miola.",
        GENOLL: "Articulació que uneix la cuixa i la cama.",
        GIRAFA: "Animal molt alt amb el coll llarg.",
        GOMA: "Objecte que serveix per esborrar llapis.",
        GOS: "Animal domèstic que lladra.",
        GRIS: "Color entre el blanc i el negre.",
        GROC: "Color del sol o d'una llimona.",
        GUINEU: "Animal del bosc semblant a un gos, sovint de color rogenc.",
        KIWI: "Fruita petita amb pell marró i interior verd.",
        LILA: "Color entre el blau i el rosa.",
        LLAPIS: "Eina per escriure o dibuixar.",
        LLEO: "Gran felí amb crinera.",
        LLET: "Líquid blanc que beuen les cries de molts mamífers.",
        LLIBRE: "Conjunt de pàgines per llegir o estudiar.",
        LLOP: "Animal salvatge semblant a un gos.",
        LLUNA: "Satèl·lit que gira al voltant de la Terra.",
        MA: "Part del cos amb dits per agafar coses.",
        MADUIXA: "Fruita vermella petita amb llavors per fora.",
        MARRO: "Color de la fusta o de la xocolata.",
        MART: "Planeta rogenc del sistema solar.",
        MELO: "Fruita gran, rodona i refrescant.",
        MESTRA: "Dona que ensenya a l'escola.",
        METGE: "Persona que cuida la salut i tracta malalties.",
        METRO: "Tren urbà que circula per la ciutat, sovint sota terra.",
        MOTO: "Vehicle de dues rodes amb motor.",
        MOTXILLA: "Bossa amb nanses que es porta a l'esquena.",
        MUSSOL: "Ocell nocturn amb ulls grossos.",
        NAS: "Part del cos amb què olorem i respirem.",
        NEGRE: "Color de la nit sense llum.",
        ORBITA: "Camí que fa un astre al voltant d'un altre.",
        ORELLA: "Part del cos amb què sentim.",
        OS: "Animal gran i fort del bosc.",
        OU: "Aliment amb closca que ponen aus com la gallina.",
        OVELLA: "Animal domèstic que dona llana.",
        PA: "Aliment fet amb farina i fornejat.",
        PAGES: "Persona que treballa la terra o cuida animals de granja.",
        PASTA: "Aliment fet amb farina que es cou amb aigua.",
        PASTANAGA: "Verdura allargada de color taronja.",
        PATATA: "Tubercle que creix sota terra.",
        PEIX: "Animal que viu a l'aigua i respira per brànquies.",
        PERA: "Fruita dolça amb la part de sota més ampla.",
        PEU: "Part del cos que ens ajuda a sostenir-nos i caminar.",
        PINTOR: "Persona que pinta parets, objectes o quadres.",
        PISSARRA: "Superfície on s'escriu a classe.",
        PLANETA: "Astre que gira al voltant d'una estrella.",
        PLATAN: "Fruita allargada i groga.",
        POMA: "Fruita rodona que pot ser vermella, verda o groga.",
        PROFESSORA: "Dona que ensenya en una escola o institut.",
        QUADERN: "Llibret de fulls per escriure o dibuixar.",
        RAIM: "Conjunt de grans petits de fruita que pengen junts.",
        REGLE: "Eina recta per mesurar o dibuixar línies.",
        ROSA: "Color suau semblant al d'algunes flors.",
        SOL: "Estrella que dona llum i calor a la Terra.",
        TARONJA: "Fruita rodona i també color ataronjat.",
        TEIXO: "Animal de bosc, robust i de potes curtes.",
        TIGRE: "Gran felí amb ratlles fosques.",
        TISORES: "Eina per tallar paper o roba.",
        TOMAQUET: "Fruit vermell que moltes vegades fem servir com una verdura.",
        TREN: "Vehicle format per vagons que va per vies.",
        ULL: "Part del cos amb què veiem.",
        VACA: "Animal domèstic que dona llet.",
        VAIXELL: "Vehicle que navega per l'aigua.",
        VENUS: "Planeta proper a la Terra.",
        VERD: "Color de l'herba o de moltes fulles.",
        VERMELL: "Color de la sang o de moltes maduixes.",
        ZEBRA: "Animal semblant al cavall amb ratlles blanques i negres.",
      }),
      en: Object.freeze({
        APPLE: "A round fruit that can be red, green, or yellow.",
        ARM: "The body part that goes from the shoulder to the hand.",
        BACK: "The rear part of the body trunk.",
        BACKPACK: "A bag with straps that is carried on the back.",
        BADGER: "A sturdy wild animal with short legs that lives on land.",
        BAKER: "A person who makes or sells bread.",
        BANANA: "A long yellow fruit.",
        BEAR: "A large, strong wild animal.",
        BIKE: "A two-wheeled vehicle moved with pedals.",
        BLACK: "The color of a night with no light.",
        BLUE: "The color of the sky on a clear day.",
        BOARD: "A surface used for writing in class.",
        BOAT: "A vehicle that travels on water.",
        BOOK: "A set of pages for reading or studying.",
        BREAD: "Food made from flour and baked.",
        BROWN: "The color of wood or chocolate.",
        BUS: "A large vehicle that carries passengers.",
        CABBAGE: "A round vegetable with tightly packed leaves.",
        CAR: "A four-wheeled vehicle for roads.",
        CARROT: "A long orange vegetable.",
        CAT: "A pet animal that meows.",
        CHEESE: "Food that is usually made from milk.",
        CHERRY: "A small round fruit that is often red.",
        COOK: "A person who prepares food.",
        COW: "A farm animal that gives milk.",
        CUCUMBER: "A long green vegetable that is fresh and crunchy.",
        CYAN: "A very light blue color.",
        DEER: "An animal with long legs that may have antlers.",
        DOCTOR: "A person who cares for health and treats illnesses.",
        DOG: "A pet animal that barks.",
        EAR: "The body part used for hearing.",
        EGG: "Food with a shell that birds such as hens lay.",
        ELEPHANT: "A very large animal with a trunk.",
        ERASER: "An object used to rub out pencil marks.",
        EYE: "The body part used for seeing.",
        FARMER: "A person who works the land or looks after farm animals.",
        FINGER: "One of the long parts of the hand.",
        FIREFIGHTER: "A person who puts out fires and helps in emergencies.",
        FISH: "An animal that lives in water and breathes through gills.",
        FOOT: "The body part that helps us stand and walk.",
        FOX: "A wild animal like a dog, often with reddish fur.",
        GARLIC: "A white bulb with a strong taste used in cooking.",
        GIRAFFE: "A very tall animal with a long neck.",
        GRAPE: "A small fruit that grows in bunches.",
        GREEN: "The color of grass or many leaves.",
        GREY: "A color between black and white.",
        HAND: "The body part with fingers for holding things.",
        HEAD: "The body part where the eyes, nose, and mouth are.",
        HORSE: "A large animal that can run fast and carry people.",
        KIWI: "A small fruit with brown skin and green inside.",
        KNEE: "The joint between the thigh and the lower leg.",
        LEG: "The body part that goes from the hip to the foot.",
        LETTUCE: "A leafy green vegetable often used in salads.",
        LION: "A big cat with a mane.",
        MARS: "The reddish planet in the solar system.",
        MEAT: "Food that comes from animals.",
        MELON: "A large, round, refreshing fruit.",
        METRO: "A city train that often travels underground.",
        MILK: "A white liquid that young mammals drink.",
        MOON: "The natural satellite that goes around Earth.",
        MOTORBIKE: "A two-wheeled vehicle with an engine.",
        MOUTH: "The body part used for eating and speaking.",
        NOSE: "The body part used for smelling and breathing.",
        NOTEBOOK: "A book of pages for writing notes.",
        ONION: "A round vegetable with layers and a strong taste.",
        ORANGE: "A round fruit and also a bright color.",
        ORBIT: "The path one object follows around another in space.",
        OWL: "A night bird with large eyes.",
        PAINTER: "A person who paints walls, objects, or pictures.",
        PASTA: "Food made from flour that is cooked in water.",
        PEAR: "A sweet fruit that is wider at the bottom.",
        PENCIL: "A tool used for writing or drawing.",
        PINK: "A soft color like some flowers.",
        PLANE: "A vehicle that flies through the air.",
        PLANET: "A space object that moves around a star.",
        POSTMAN: "A person who delivers letters and parcels.",
        POTATO: "A tuber that grows underground.",
        PURPLE: "A color between blue and red.",
        RABBIT: "A small animal with long ears.",
        RED: "The color of blood or many strawberries.",
        RICE: "A small white grain that is often cooked boiled.",
        ROCKET: "A vehicle that travels into space.",
        RULER: "A straight tool for measuring or drawing lines.",
        SCISSORS: "A tool used to cut paper or fabric.",
        SHEEP: "A farm animal that gives wool.",
        SQUIRREL: "A small animal that climbs trees and eats nuts.",
        STAR: "A space object that shines with its own light.",
        STRAWBERRY: "A small red fruit with seeds on the outside.",
        STUDENT: "A person who learns at school.",
        SUN: "The star that gives Earth light and heat.",
        TEACHER: "A person who teaches at school.",
        TIGER: "A big cat with dark stripes.",
        TOMATO: "A red fruit that is often used like a vegetable.",
        TRAIN: "A vehicle made of carriages that runs on tracks.",
        VENUS: "A planet close to Earth.",
        WHITE: "The color of snow or paper.",
        WOLF: "A wild animal like a dog.",
        YELLOW: "The color of the sun or a ripe banana.",
        ZEBRA: "An animal like a horse with black and white stripes.",
      }),
    }),
    samplePuzzles: Object.freeze({
      es: Object.freeze([
        Object.freeze({
          title: "Animales del bosque",
          difficulty: "easy",
          size: "auto",
          words: ["ardilla", "zorro", "ciervo", "tejón", "búho", "lobo", "conejo", "oso"].join("\n"),
        }),
        Object.freeze({
          title: "Alimentos saludables",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "col", "naranja", "pera", "tomate", "arroz", "leche"].join("\n"),
        }),
        Object.freeze({
          title: "Frutas del mercado",
          difficulty: "easy",
          size: "auto",
          words: ["manzana", "pera", "plátano", "naranja", "kiwi", "melón", "uva", "cereza"].join("\n"),
        }),
        Object.freeze({
          title: "Verduras del huerto",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "cebolla", "col", "lechuga", "tomate", "pepino", "ajo"].join("\n"),
        }),
        Object.freeze({
          title: "Transportes de la ciudad",
          difficulty: "easy",
          size: "auto",
          words: ["coche", "tren", "barco", "avión", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficios del barrio",
          difficulty: "medium",
          size: "auto",
          words: ["maestra", "médico", "cocinero", "pintor", "bombero", "panadero", "granjero", "cartero"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "órbita", "marte", "venus", "luna", "cohete", "estrella"].join("\n"),
        }),
      ]),
      ca: Object.freeze([
        Object.freeze({
          title: "Animals del bosc",
          difficulty: "easy",
          size: "auto",
          words: ["esquirol", "guineu", "cérvol", "teixó", "mussol", "llop", "conill", "os"].join("\n"),
        }),
        Object.freeze({
          title: "Aliments saludables",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "col", "taronja", "pera", "tomàquet", "arròs", "llet"].join("\n"),
        }),
        Object.freeze({
          title: "Fruites del mercat",
          difficulty: "easy",
          size: "auto",
          words: ["poma", "pera", "plàtan", "taronja", "kiwi", "meló", "raim", "cirera"].join("\n"),
        }),
        Object.freeze({
          title: "Verdures de l'hort",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "ceba", "col", "enciam", "tomàquet", "cogombre", "all"].join("\n"),
        }),
        Object.freeze({
          title: "Transports de la ciutat",
          difficulty: "easy",
          size: "auto",
          words: ["cotxe", "tren", "vaixell", "avió", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficis del barri",
          difficulty: "medium",
          size: "auto",
          words: ["mestra", "metge", "cuiner", "pintor", "bomber", "forner", "pagès", "carter"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "òrbita", "mart", "venus", "lluna", "coet", "estrella"].join("\n"),
        }),
      ]),
      en: Object.freeze([
        Object.freeze({
          title: "Forest animals",
          difficulty: "easy",
          size: "auto",
          words: ["squirrel", "fox", "deer", "badger", "owl", "wolf", "rabbit", "bear"].join("\n"),
        }),
        Object.freeze({
          title: "Healthy food",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "cabbage", "orange", "pear", "tomato", "rice", "milk"].join("\n"),
        }),
        Object.freeze({
          title: "Market fruits",
          difficulty: "easy",
          size: "auto",
          words: ["apple", "pear", "banana", "orange", "kiwi", "melon", "grape", "cherry"].join("\n"),
        }),
        Object.freeze({
          title: "Garden vegetables",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "onion", "cabbage", "lettuce", "tomato", "cucumber", "garlic"].join("\n"),
        }),
        Object.freeze({
          title: "City transport",
          difficulty: "easy",
          size: "auto",
          words: ["car", "train", "boat", "plane", "bike", "motorbike", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Neighborhood jobs",
          difficulty: "medium",
          size: "auto",
          words: ["teacher", "doctor", "cook", "painter", "firefighter", "baker", "farmer", "postman"].join("\n"),
        }),
        Object.freeze({
          title: "Solar system",
          difficulty: "medium",
          size: "auto",
          words: ["sun", "planet", "orbit", "mars", "venus", "moon", "rocket", "star"].join("\n"),
        }),
      ]),
    }),
  });
})(typeof window !== "undefined" ? window : globalThis);
