(function (global) {
  "use strict";

  // Static content lives outside app.js so the game logic stays focused.
  global.WORD_SEARCH_DATA = Object.freeze({
    vocabulary: Object.freeze({
      es: Object.freeze({
        animals: Object.freeze({
          label: "Animales",
          words: Object.freeze([
            "perro",
            "gato",
            "elefante",
            "jirafa",
            "león",
            "tigre",
            "cebra",
            "oso",
            "lobo",
            "conejo",
            "ciervo",
            "zorro",
            "caballo",
            "vaca",
            "oveja",
            "ardilla",
            "tejón",
          ]),
        }),
        fruits: Object.freeze({
          label: "Frutas",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "naranja",
            "kiwi",
            "melón",
            "uva",
            "cereza",
            "fresa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verduras",
          words: Object.freeze([
            "zanahoria",
            "patata",
            "cebolla",
            "col",
            "lechuga",
            "tomate",
            "pepino",
            "ajo",
          ]),
        }),
        colors: Object.freeze({
          label: "Colores",
          words: Object.freeze([
            "rojo",
            "azul",
            "verde",
            "amarillo",
            "naranja",
            "rosa",
            "morado",
            "blanco",
            "negro",
            "gris",
            "marrón",
            "celeste",
          ]),
        }),
        body: Object.freeze({
          label: "Cuerpo",
          words: Object.freeze([
            "cabeza",
            "mano",
            "pie",
            "brazo",
            "pierna",
            "ojo",
            "boca",
            "nariz",
            "oreja",
            "dedo",
            "rodilla",
            "espalda",
          ]),
        }),
        food: Object.freeze({
          label: "Comida",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "pan",
            "leche",
            "huevo",
            "queso",
            "arroz",
            "pasta",
            "carne",
            "pescado",
            "tomate",
          ]),
        }),
        transports: Object.freeze({
          label: "Transportes",
          words: Object.freeze([
            "coche",
            "tren",
            "barco",
            "avión",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escuela",
          words: Object.freeze([
            "lápiz",
            "goma",
            "libro",
            "mochila",
            "pizarra",
            "tijeras",
            "regla",
            "cuaderno",
            "profesora",
            "alumno",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficios",
          words: Object.freeze([
            "maestra",
            "médico",
            "cocinero",
            "pintor",
            "bombero",
            "panadero",
            "granjero",
            "cartero",
          ]),
        }),
      }),
      ca: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "gos",
            "gat",
            "elefant",
            "girafa",
            "lleó",
            "tigre",
            "zebra",
            "os",
            "llop",
            "conill",
            "cérvol",
            "guineu",
            "cavall",
            "vaca",
            "ovella",
            "esquirol",
            "teixó",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruites",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "taronja",
            "kiwi",
            "meló",
            "raim",
            "cirera",
            "maduixa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verdures",
          words: Object.freeze([
            "pastanaga",
            "patata",
            "ceba",
            "col",
            "enciam",
            "tomaquet",
            "cogombre",
            "all",
          ]),
        }),
        colors: Object.freeze({
          label: "Colors",
          words: Object.freeze([
            "vermell",
            "blau",
            "verd",
            "groc",
            "taronja",
            "rosa",
            "lila",
            "blanc",
            "negre",
            "gris",
            "marró",
            "celest",
          ]),
        }),
        body: Object.freeze({
          label: "Cos",
          words: Object.freeze([
            "cap",
            "mà",
            "peu",
            "braç",
            "cama",
            "ull",
            "boca",
            "nas",
            "orella",
            "dit",
            "genoll",
            "esquena",
          ]),
        }),
        food: Object.freeze({
          label: "Menjar",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "pa",
            "llet",
            "ou",
            "formatge",
            "arròs",
            "pasta",
            "carn",
            "peix",
            "tomaquet",
          ]),
        }),
        transports: Object.freeze({
          label: "Transports",
          words: Object.freeze([
            "cotxe",
            "tren",
            "vaixell",
            "avió",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escola",
          words: Object.freeze([
            "llapis",
            "goma",
            "llibre",
            "motxilla",
            "pissarra",
            "tisores",
            "regle",
            "quadern",
            "professora",
            "alumne",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficis",
          words: Object.freeze([
            "mestra",
            "metge",
            "cuiner",
            "pintor",
            "bomber",
            "forner",
            "pagès",
            "carter",
          ]),
        }),
      }),
      en: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "dog",
            "cat",
            "elephant",
            "giraffe",
            "lion",
            "tiger",
            "zebra",
            "bear",
            "wolf",
            "rabbit",
            "deer",
            "fox",
            "horse",
            "cow",
            "sheep",
            "squirrel",
            "badger",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruits",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "orange",
            "kiwi",
            "melon",
            "grape",
            "cherry",
            "strawberry",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Vegetables",
          words: Object.freeze([
            "carrot",
            "potato",
            "onion",
            "cabbage",
            "lettuce",
            "tomato",
            "cucumber",
            "garlic",
          ]),
        }),
        colors: Object.freeze({
          label: "Colors",
          words: Object.freeze([
            "red",
            "blue",
            "green",
            "yellow",
            "orange",
            "pink",
            "purple",
            "white",
            "black",
            "grey",
            "brown",
            "cyan",
          ]),
        }),
        body: Object.freeze({
          label: "Body",
          words: Object.freeze([
            "head",
            "hand",
            "foot",
            "arm",
            "leg",
            "eye",
            "mouth",
            "nose",
            "ear",
            "finger",
            "knee",
            "back",
          ]),
        }),
        food: Object.freeze({
          label: "Food",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "bread",
            "milk",
            "egg",
            "cheese",
            "rice",
            "pasta",
            "meat",
            "fish",
            "tomato",
          ]),
        }),
        transports: Object.freeze({
          label: "Transport",
          words: Object.freeze([
            "car",
            "train",
            "boat",
            "plane",
            "bike",
            "motorbike",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "School",
          words: Object.freeze([
            "pencil",
            "eraser",
            "book",
            "backpack",
            "board",
            "scissors",
            "ruler",
            "notebook",
            "teacher",
            "student",
          ]),
        }),
        jobs: Object.freeze({
          label: "Jobs",
          words: Object.freeze([
            "teacher",
            "doctor",
            "cook",
            "painter",
            "firefighter",
            "baker",
            "farmer",
            "postman",
          ]),
        }),
      }),
    }),
    samplePuzzles: Object.freeze({
      es: Object.freeze([
        Object.freeze({
          title: "Animales del bosque",
          difficulty: "easy",
          size: "auto",
          words: ["ardilla", "zorro", "ciervo", "tejón", "búho", "lobo", "conejo", "oso"].join("\n"),
        }),
        Object.freeze({
          title: "Alimentos saludables",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "col", "naranja", "pera", "tomate", "arroz", "leche"].join("\n"),
        }),
        Object.freeze({
          title: "Frutas del mercado",
          difficulty: "easy",
          size: "auto",
          words: ["manzana", "pera", "plátano", "naranja", "kiwi", "melón", "uva", "cereza"].join("\n"),
        }),
        Object.freeze({
          title: "Verduras del huerto",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "cebolla", "col", "lechuga", "tomate", "pepino", "ajo"].join("\n"),
        }),
        Object.freeze({
          title: "Transportes de la ciudad",
          difficulty: "easy",
          size: "auto",
          words: ["coche", "tren", "barco", "avión", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficios del barrio",
          difficulty: "medium",
          size: "auto",
          words: ["maestra", "médico", "cocinero", "pintor", "bombero", "panadero", "granjero", "cartero"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "órbita", "marte", "venus", "luna", "cohete", "estrella"].join("\n"),
        }),
      ]),
      ca: Object.freeze([
        Object.freeze({
          title: "Animals del bosc",
          difficulty: "easy",
          size: "auto",
          words: ["esquirol", "guineu", "cérvol", "teixó", "mussol", "llop", "conill", "os"].join("\n"),
        }),
        Object.freeze({
          title: "Aliments saludables",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "col", "taronja", "pera", "tomaquet", "arròs", "llet"].join("\n"),
        }),
        Object.freeze({
          title: "Fruites del mercat",
          difficulty: "easy",
          size: "auto",
          words: ["poma", "pera", "plàtan", "taronja", "kiwi", "meló", "raim", "cirera"].join("\n"),
        }),
        Object.freeze({
          title: "Verdures de l'hort",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "ceba", "col", "enciam", "tomaquet", "cogombre", "all"].join("\n"),
        }),
        Object.freeze({
          title: "Transports de la ciutat",
          difficulty: "easy",
          size: "auto",
          words: ["cotxe", "tren", "vaixell", "avió", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficis del barri",
          difficulty: "medium",
          size: "auto",
          words: ["mestra", "metge", "cuiner", "pintor", "bomber", "forner", "pagès", "carter"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "òrbita", "mart", "venus", "lluna", "coet", "estrella"].join("\n"),
        }),
      ]),
      en: Object.freeze([
        Object.freeze({
          title: "Forest animals",
          difficulty: "easy",
          size: "auto",
          words: ["squirrel", "fox", "deer", "badger", "owl", "wolf", "rabbit", "bear"].join("\n"),
        }),
        Object.freeze({
          title: "Healthy food",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "cabbage", "orange", "pear", "tomato", "rice", "milk"].join("\n"),
        }),
        Object.freeze({
          title: "Market fruits",
          difficulty: "easy",
          size: "auto",
          words: ["apple", "pear", "banana", "orange", "kiwi", "melon", "grape", "cherry"].join("\n"),
        }),
        Object.freeze({
          title: "Garden vegetables",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "onion", "cabbage", "lettuce", "tomato", "cucumber", "garlic"].join("\n"),
        }),
        Object.freeze({
          title: "City transport",
          difficulty: "easy",
          size: "auto",
          words: ["car", "train", "boat", "plane", "bike", "motorbike", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Neighborhood jobs",
          difficulty: "medium",
          size: "auto",
          words: ["teacher", "doctor", "cook", "painter", "firefighter", "baker", "farmer", "postman"].join("\n"),
        }),
        Object.freeze({
          title: "Solar system",
          difficulty: "medium",
          size: "auto",
          words: ["sun", "planet", "orbit", "mars", "venus", "moon", "rocket", "star"].join("\n"),
        }),
      ]),
    }),
  });
})(typeof window !== "undefined" ? window : globalThis);
