(function (global) {
  "use strict";

  // Static content lives outside app.js so the game logic stays focused.
  global.WORD_SEARCH_DATA = Object.freeze({
    vocabulary: Object.freeze({
      es: Object.freeze({
        animals: Object.freeze({
          label: "Animales",
          words: Object.freeze([
            "perro",
            "gato",
            "elefante",
            "jirafa",
            "león",
            "tigre",
            "cebra",
            "oso",
            "lobo",
            "conejo",
            "ciervo",
            "zorro",
            "caballo",
            "vaca",
            "oveja",
            "ardilla",
            "tejón",
          ]),
        }),
        fruits: Object.freeze({
          label: "Frutas",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "naranja",
            "kiwi",
            "melón",
            "uva",
            "cereza",
            "fresa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verduras",
          words: Object.freeze([
            "zanahoria",
            "patata",
            "cebolla",
            "col",
            "lechuga",
            "tomate",
            "pepino",
            "ajo",
          ]),
        }),
        colors: Object.freeze({
          label: "Colores",
          words: Object.freeze([
            "rojo",
            "azul",
            "verde",
            "amarillo",
            "naranja",
            "rosa",
            "morado",
            "blanco",
            "negro",
            "gris",
            "marrón",
            "celeste",
          ]),
        }),
        body: Object.freeze({
          label: "Cuerpo",
          words: Object.freeze([
            "cabeza",
            "mano",
            "pie",
            "brazo",
            "pierna",
            "ojo",
            "boca",
            "nariz",
            "oreja",
            "dedo",
            "rodilla",
            "espalda",
          ]),
        }),
        food: Object.freeze({
          label: "Comida",
          words: Object.freeze([
            "manzana",
            "pera",
            "plátano",
            "pan",
            "leche",
            "huevo",
            "queso",
            "arroz",
            "pasta",
            "carne",
            "pescado",
            "tomate",
          ]),
        }),
        transports: Object.freeze({
          label: "Transportes",
          words: Object.freeze([
            "coche",
            "tren",
            "barco",
            "avión",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escuela",
          words: Object.freeze([
            "lápiz",
            "goma",
            "libro",
            "mochila",
            "pizarra",
            "tijeras",
            "regla",
            "cuaderno",
            "profesora",
            "alumno",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficios",
          words: Object.freeze([
            "maestra",
            "médico",
            "cocinero",
            "pintor",
            "bombero",
            "panadero",
            "granjero",
            "cartero",
          ]),
        }),
        autumn: Object.freeze({
          label: "Otoño y Castañada",
          words: Object.freeze([
            "castaña",
            "boniato",
            "panellet",
            "castañera",
            "seta",
            "hoja",
            "granada",
            "membrillo",
            "bellota",
            "paraguas",
          ]),
        }),
        christmas: Object.freeze({
          label: "Navidad",
          words: Object.freeze([
            "árbol",
            "estrella",
            "regalo",
            "belén",
            "turrón",
            "campana",
            "reyes",
            "villancico",
            "vela",
            "polvorón",
          ]),
        }),
        calendar: Object.freeze({
          label: "Días y estaciones",
          words: Object.freeze([
            "lunes",
            "martes",
            "miércoles",
            "jueves",
            "viernes",
            "sábado",
            "domingo",
            "primavera",
            "verano",
            "otoño",
            "invierno",
          ]),
        }),
        clothes: Object.freeze({
          label: "Ropa",
          words: Object.freeze([
            "camiseta",
            "pantalón",
            "jersey",
            "chaqueta",
            "falda",
            "calcetín",
            "zapato",
            "bufanda",
            "gorra",
            "guante",
          ]),
        }),
        house: Object.freeze({
          label: "Casa",
          words: Object.freeze([
            "cocina",
            "comedor",
            "habitación",
            "baño",
            "ventana",
            "puerta",
            "cama",
            "silla",
            "mesa",
            "sofá",
          ]),
        }),
        family: Object.freeze({
          label: "Familia",
          words: Object.freeze([
            "madre",
            "padre",
            "hermano",
            "hermana",
            "abuelo",
            "abuela",
            "tío",
            "tía",
            "primo",
            "bebé",
          ]),
        }),
        emotions: Object.freeze({
          label: "Emociones",
          words: Object.freeze([
            "alegría",
            "tristeza",
            "miedo",
            "rabia",
            "calma",
            "sorpresa",
            "vergüenza",
            "amor",
            "asco",
            "nostalgia",
          ]),
        }),
        sports: Object.freeze({
          label: "Deportes",
          words: Object.freeze([
            "fútbol",
            "baloncesto",
            "natación",
            "tenis",
            "ciclismo",
            "balonmano",
            "atletismo",
            "patinaje",
            "gimnasia",
            "pelota",
          ]),
        }),
        weather: Object.freeze({
          label: "Tiempo",
          words: Object.freeze([
            "sol",
            "lluvia",
            "nube",
            "viento",
            "nieve",
            "tormenta",
            "rayo",
            "niebla",
            "calor",
            "frío",
          ]),
        }),
      }),
      ca: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "gos",
            "gat",
            "elefant",
            "girafa",
            "lleó",
            "tigre",
            "zebra",
            "os",
            "llop",
            "conill",
            "cérvol",
            "guineu",
            "cavall",
            "vaca",
            "ovella",
            "esquirol",
            "teixó",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruites",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "taronja",
            "kiwi",
            "meló",
            "raïm",
            "cirera",
            "maduixa",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Verdures",
          words: Object.freeze([
            "pastanaga",
            "patata",
            "ceba",
            "col",
            "enciam",
            "tomàquet",
            "cogombre",
            "all",
          ]),
        }),
        colors: Object.freeze({
          label: "Colors",
          words: Object.freeze([
            "vermell",
            "blau",
            "verd",
            "groc",
            "taronja",
            "rosa",
            "lila",
            "blanc",
            "negre",
            "gris",
            "marró",
            "celest",
          ]),
        }),
        body: Object.freeze({
          label: "Cos",
          words: Object.freeze([
            "cap",
            "mà",
            "peu",
            "braç",
            "cama",
            "ull",
            "boca",
            "nas",
            "orella",
            "dit",
            "genoll",
            "esquena",
          ]),
        }),
        food: Object.freeze({
          label: "Menjar",
          words: Object.freeze([
            "poma",
            "pera",
            "plàtan",
            "pa",
            "llet",
            "ou",
            "formatge",
            "arròs",
            "pasta",
            "carn",
            "peix",
            "tomàquet",
          ]),
        }),
        transports: Object.freeze({
          label: "Transports",
          words: Object.freeze([
            "cotxe",
            "tren",
            "vaixell",
            "avió",
            "bici",
            "moto",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "Escola",
          words: Object.freeze([
            "llapis",
            "goma",
            "llibre",
            "motxilla",
            "pissarra",
            "tisores",
            "regle",
            "quadern",
            "professora",
            "alumne",
          ]),
        }),
        jobs: Object.freeze({
          label: "Oficis",
          words: Object.freeze([
            "mestra",
            "metge",
            "cuiner",
            "pintor",
            "bomber",
            "forner",
            "pagès",
            "carter",
          ]),
        }),
        autumn: Object.freeze({
          label: "Tardor i Castanyada",
          words: Object.freeze([
            "castanya",
            "moniato",
            "panellet",
            "castanyera",
            "bolet",
            "fulla",
            "magrana",
            "codony",
            "gla",
            "paraigua",
          ]),
        }),
        christmas: Object.freeze({
          label: "Nadal",
          words: Object.freeze([
            "arbre",
            "estrella",
            "regal",
            "pessebre",
            "tió",
            "torró",
            "campana",
            "caganer",
            "neules",
            "espelma",
          ]),
        }),
        calendar: Object.freeze({
          label: "Dies i estacions",
          words: Object.freeze([
            "dilluns",
            "dimarts",
            "dimecres",
            "dijous",
            "divendres",
            "dissabte",
            "diumenge",
            "primavera",
            "estiu",
            "tardor",
            "hivern",
          ]),
        }),
        clothes: Object.freeze({
          label: "Roba",
          words: Object.freeze([
            "samarreta",
            "pantalons",
            "jersei",
            "jaqueta",
            "faldilla",
            "mitjó",
            "sabata",
            "bufanda",
            "gorra",
            "guant",
          ]),
        }),
        house: Object.freeze({
          label: "Casa",
          words: Object.freeze([
            "cuina",
            "menjador",
            "habitació",
            "lavabo",
            "finestra",
            "porta",
            "llit",
            "cadira",
            "taula",
            "sofà",
          ]),
        }),
        family: Object.freeze({
          label: "Família",
          words: Object.freeze([
            "mare",
            "pare",
            "germà",
            "germana",
            "avi",
            "àvia",
            "oncle",
            "tia",
            "cosí",
            "nadó",
          ]),
        }),
        emotions: Object.freeze({
          label: "Emocions",
          words: Object.freeze([
            "alegria",
            "tristesa",
            "por",
            "ràbia",
            "calma",
            "sorpresa",
            "vergonya",
            "amor",
            "fàstic",
            "enyorança",
          ]),
        }),
        sports: Object.freeze({
          label: "Esports",
          words: Object.freeze([
            "futbol",
            "bàsquet",
            "natació",
            "tennis",
            "ciclisme",
            "handbol",
            "atletisme",
            "patinatge",
            "gimnàstica",
            "pilota",
          ]),
        }),
        weather: Object.freeze({
          label: "Temps",
          words: Object.freeze([
            "sol",
            "pluja",
            "núvol",
            "vent",
            "neu",
            "tempesta",
            "llamp",
            "boira",
            "calor",
            "fred",
          ]),
        }),
      }),
      en: Object.freeze({
        animals: Object.freeze({
          label: "Animals",
          words: Object.freeze([
            "dog",
            "cat",
            "elephant",
            "giraffe",
            "lion",
            "tiger",
            "zebra",
            "bear",
            "wolf",
            "rabbit",
            "deer",
            "fox",
            "horse",
            "cow",
            "sheep",
            "squirrel",
            "badger",
          ]),
        }),
        fruits: Object.freeze({
          label: "Fruits",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "orange",
            "kiwi",
            "melon",
            "grape",
            "cherry",
            "strawberry",
          ]),
        }),
        vegetables: Object.freeze({
          label: "Vegetables",
          words: Object.freeze([
            "carrot",
            "potato",
            "onion",
            "cabbage",
            "lettuce",
            "tomato",
            "cucumber",
            "garlic",
          ]),
        }),
        colors: Object.freeze({
          label: "Colours",
          words: Object.freeze([
            "red",
            "blue",
            "green",
            "yellow",
            "orange",
            "pink",
            "purple",
            "white",
            "black",
            "grey",
            "brown",
            "cyan",
          ]),
        }),
        body: Object.freeze({
          label: "Body",
          words: Object.freeze([
            "head",
            "hand",
            "foot",
            "arm",
            "leg",
            "eye",
            "mouth",
            "nose",
            "ear",
            "finger",
            "knee",
            "back",
          ]),
        }),
        food: Object.freeze({
          label: "Food",
          words: Object.freeze([
            "apple",
            "pear",
            "banana",
            "bread",
            "milk",
            "egg",
            "cheese",
            "rice",
            "pasta",
            "meat",
            "fish",
            "tomato",
          ]),
        }),
        transports: Object.freeze({
          label: "Transport",
          words: Object.freeze([
            "car",
            "train",
            "boat",
            "plane",
            "bike",
            "motorbike",
            "bus",
            "metro",
          ]),
        }),
        school: Object.freeze({
          label: "School",
          words: Object.freeze([
            "pencil",
            "eraser",
            "book",
            "backpack",
            "board",
            "scissors",
            "ruler",
            "notebook",
            "teacher",
            "student",
          ]),
        }),
        jobs: Object.freeze({
          label: "Jobs",
          words: Object.freeze([
            "teacher",
            "doctor",
            "cook",
            "painter",
            "firefighter",
            "baker",
            "farmer",
            "postman",
          ]),
        }),
        autumn: Object.freeze({
          label: "Autumn",
          words: Object.freeze([
            "chestnut",
            "acorn",
            "mushroom",
            "leaf",
            "pumpkin",
            "umbrella",
            "raincoat",
            "harvest",
            "puddle",
            "hedgehog",
          ]),
        }),
        christmas: Object.freeze({
          label: "Christmas",
          words: Object.freeze([
            "tree",
            "star",
            "present",
            "reindeer",
            "sleigh",
            "stocking",
            "carol",
            "bell",
            "candle",
            "snowman",
          ]),
        }),
        calendar: Object.freeze({
          label: "Days and seasons",
          words: Object.freeze([
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
            "spring",
            "summer",
            "autumn",
            "winter",
          ]),
        }),
        clothes: Object.freeze({
          label: "Clothes",
          words: Object.freeze([
            "shirt",
            "trousers",
            "jumper",
            "jacket",
            "skirt",
            "sock",
            "shoe",
            "scarf",
            "cap",
            "glove",
          ]),
        }),
        house: Object.freeze({
          label: "Home",
          words: Object.freeze([
            "kitchen",
            "bedroom",
            "bathroom",
            "window",
            "door",
            "bed",
            "chair",
            "table",
            "sofa",
            "garden",
          ]),
        }),
        family: Object.freeze({
          label: "Family",
          words: Object.freeze([
            "mother",
            "father",
            "brother",
            "sister",
            "grandpa",
            "grandma",
            "uncle",
            "aunt",
            "cousin",
            "baby",
          ]),
        }),
        emotions: Object.freeze({
          label: "Feelings",
          words: Object.freeze([
            "happy",
            "sad",
            "scared",
            "angry",
            "calm",
            "surprised",
            "shy",
            "tired",
            "bored",
            "excited",
          ]),
        }),
        sports: Object.freeze({
          label: "Sports",
          words: Object.freeze([
            "football",
            "basketball",
            "swimming",
            "tennis",
            "cycling",
            "handball",
            "running",
            "skating",
            "gymnastics",
            "ball",
          ]),
        }),
        weather: Object.freeze({
          label: "Weather",
          words: Object.freeze([
            "sun",
            "rain",
            "cloud",
            "wind",
            "snow",
            "storm",
            "lightning",
            "fog",
            "hot",
            "cold",
          ]),
        }),
      }),
    }),
    definitions: Object.freeze({
      es: Object.freeze({
        ABUELA: "La madre de tu madre o de tu padre.",
        ABUELO: "El padre de tu madre o de tu padre.",
        AJO: "Bulbo blanco con sabor fuerte que se usa para cocinar.",
        ALEGRIA: "Lo que sientes cuando estás contento.",
        ALUMNO: "Persona que aprende en la escuela.",
        AMARILLO: "Color del sol o de un plátano maduro.",
        AMOR: "Lo que sientes cuando quieres mucho a alguien.",
        ARBOL: "Planta grande con tronco y ramas; en Navidad decoramos uno.",
        ARDILLA: "Animal pequeño que trepa a los árboles y come frutos secos.",
        ARROZ: "Grano pequeño y blanco que se cocina muchas veces hervido.",
        ASCO: "Lo que sientes ante algo sucio o que huele mal.",
        ATLETISMO: "Deportes de correr, saltar y lanzar.",
        AVION: "Vehículo que vuela por el aire.",
        AZUL: "Color del cielo en un día despejado.",
        BALONCESTO: "Deporte en el que hay que meter el balón por una canasta.",
        BALONMANO: "Deporte en el que dos equipos marcan goles lanzando el balón con la mano.",
        BAÑO: "Lugar de la casa donde nos lavamos.",
        BARCO: "Vehículo que navega por el agua.",
        BEBE: "Niño o niña que ha nacido hace poco.",
        BELEN: "Escena de figuritas que se monta en Navidad.",
        BELLOTA: "Fruto pequeño de la encina y del roble.",
        BICI: "Vehículo de dos ruedas que se mueve con pedales.",
        BLANCO: "Color de la nieve o del papel.",
        BOCA: "Parte del cuerpo con la que comemos y hablamos.",
        BOMBERO: "Persona que apaga incendios y ayuda en emergencias.",
        BONIATO: "Tubérculo dulce que se come asado en la Castañada.",
        BRAZO: "Parte del cuerpo que va del hombro a la mano.",
        BUFANDA: "Prenda larga que nos ponemos alrededor del cuello cuando hace frío.",
        BUHO: "Ave nocturna con ojos grandes.",
        BUS: "Vehículo grande que transporta pasajeros.",
        CABALLO: "Animal grande que puede correr mucho y llevar personas.",
        CABEZA: "Parte del cuerpo donde están los ojos, la nariz y la boca.",
        CALCETIN: "Prenda que cubre el pie dentro del zapato.",
        CALMA: "Lo que sientes cuando estás tranquilo y relajado.",
        CALOR: "Lo que sentimos cuando la temperatura es alta.",
        CAMA: "Mueble en el que dormimos.",
        CAMISETA: "Prenda ligera para la parte de arriba del cuerpo.",
        CAMPANA: "Objeto de metal que suena al golpearlo.",
        CARNE: "Alimento que es la parte blanda del cuerpo de animales como la vaca o el pollo.",
        CARTERO: "Persona que reparte cartas y paquetes.",
        CASTAÑA: "Fruto seco de color marrón que se come asado en otoño.",
        CASTAÑERA: "Mujer que vende castañas asadas en la calle.",
        CEBOLLA: "Verdura redonda con capas y sabor fuerte.",
        CEBRA: "Animal parecido al caballo con rayas blancas y negras.",
        CELESTE: "Azul claro y suave.",
        CEREZA: "Fruta pequeña y redonda, normalmente roja.",
        CHAQUETA: "Prenda de abrigo que se abrocha por delante.",
        CICLISMO: "Deporte que se hace en bicicleta.",
        CIERVO: "Animal de patas largas que puede tener cuernos.",
        COCHE: "Vehículo de cuatro ruedas para circular por carretera.",
        COCINA: "Lugar de la casa donde se prepara la comida.",
        COCINERO: "Persona que prepara la comida.",
        COHETE: "Vehículo que sube al espacio.",
        COL: "Verdura de hojas apretadas y redondeadas.",
        COMEDOR: "Lugar de la casa donde comemos.",
        CONEJO: "Animal pequeño con orejas largas.",
        CUADERNO: "Conjunto de hojas para escribir o dibujar.",
        DEDO: "Cada una de las partes alargadas de la mano.",
        DOMINGO: "Último día de la semana.",
        ELEFANTE: "Animal muy grande con trompa.",
        ESPALDA: "Parte de atrás del cuerpo, del cuello a la cintura.",
        ESTRELLA: "Astro que brilla con luz propia.",
        FALDA: "Prenda que cuelga desde la cintura.",
        FRESA: "Fruta roja pequeña con semillas por fuera.",
        FRIO: "Lo que sentimos cuando la temperatura es baja.",
        FUTBOL: "Deporte en el que dos equipos intentan marcar goles con los pies.",
        GATO: "Animal doméstico que maúlla.",
        GIMNASIA: "Deporte con saltos, volteretas y ejercicios de equilibrio.",
        GOMA: "Objeto que sirve para borrar lápiz.",
        GORRA: "Sombrero con visera para protegerse del sol.",
        GRANADA: "Fruta de otoño llena de granos rojos y jugosos.",
        GRANJERO: "Persona que trabaja en el campo o cuida animales de granja.",
        GRIS: "Color intermedio entre blanco y negro.",
        GUANTE: "Prenda que cubre la mano y cada dedo.",
        HABITACION: "Lugar de la casa donde dormimos.",
        HERMANA: "Chica que tiene la misma madre o el mismo padre que tú.",
        HERMANO: "Chico que tiene la misma madre o el mismo padre que tú.",
        HOJA: "Parte plana de las plantas que en otoño se vuelve amarilla y cae.",
        HUEVO: "Alimento con cáscara que ponen aves como la gallina.",
        INVIERNO: "La estación más fría del año.",
        JERSEY: "Prenda de lana para ir abrigado.",
        JIRAFA: "Animal alto con el cuello muy largo.",
        JUEVES: "Día de la semana que va después del miércoles.",
        KIWI: "Fruta pequeña de piel marrón e interior verde.",
        LAPIZ: "Herramienta para escribir o dibujar.",
        LECHE: "Líquido blanco que beben las crías de muchos mamíferos.",
        LECHUGA: "Verdura de hojas verdes que se usa mucho en ensaladas.",
        LEON: "Gran felino con melena.",
        LIBRO: "Conjunto de páginas para leer o estudiar.",
        LLUVIA: "Agua que cae de las nubes.",
        LOBO: "Animal salvaje parecido a un perro.",
        LUNA: "Satélite que gira alrededor de la Tierra.",
        LUNES: "Primer día de la semana.",
        MADRE: "Mujer que tiene hijos o hijas y los cuida.",
        MAESTRA: "Mujer que enseña en la escuela.",
        MANO: "Parte del cuerpo con dedos para coger cosas.",
        MANZANA: "Fruta redonda que puede ser roja, verde o amarilla.",
        MARRON: "Color de la madera o del chocolate.",
        MARTE: "Planeta rojizo del sistema solar.",
        MARTES: "Día de la semana que va después del lunes.",
        MEDICO: "Persona que cuida la salud y trata enfermedades.",
        MELON: "Fruta grande, redonda y muy refrescante.",
        MEMBRILLO: "Fruta amarilla y dura con la que se hace dulce de membrillo.",
        MESA: "Mueble con una superficie plana donde comemos o trabajamos.",
        METRO: "Tren urbano que circula por la ciudad, a menudo bajo tierra.",
        MIEDO: "Lo que sientes cuando crees que te puede pasar algo malo.",
        MIERCOLES: "Día de la mitad de la semana de colegio.",
        MOCHILA: "Bolsa con tirantes que se lleva a la espalda.",
        MORADO: "Color entre azul y rojo.",
        MOTO: "Vehículo de dos ruedas con motor.",
        NARANJA: "Fruta redonda y jugosa; su color también se llama naranja.",
        NARIZ: "Parte del cuerpo con la que olemos y respiramos.",
        NATACION: "Deporte que se hace nadando en el agua.",
        NEGRO: "Color de la noche sin luz.",
        NIEBLA: "Nube baja que no nos deja ver lejos.",
        NIEVE: "Agua helada que cae del cielo en copos blancos.",
        NOSTALGIA: "Lo que sientes cuando echas de menos a alguien o algún lugar.",
        NUBE: "Masa blanca o gris que flota en el cielo.",
        OJO: "Parte del cuerpo con la que vemos.",
        ORBITA: "Camino que sigue un astro alrededor de otro.",
        OREJA: "Parte del cuerpo con la que oímos.",
        OSO: "Animal grande y fuerte del bosque.",
        OTOÑO: "Estación del año en la que caen las hojas de los árboles.",
        OVEJA: "Animal doméstico que da lana.",
        PADRE: "Hombre que tiene hijos o hijas y los cuida.",
        PAN: "Alimento hecho con harina y horneado.",
        PANADERO: "Persona que hace o vende pan.",
        PANELLET: "Dulce pequeño de almendra típico de la Castañada.",
        PANTALON: "Prenda que cubre cada pierna por separado.",
        PARAGUAS: "Objeto que abrimos sobre la cabeza para no mojarnos con la lluvia.",
        PASTA: "Alimento hecho con harina que se cuece en agua.",
        PATATA: "Verdura que crece bajo tierra; se come frita, hervida o al horno.",
        PATINAJE: "Deporte que se hace con patines.",
        PELOTA: "Objeto redondo para jugar a muchos deportes.",
        PEPINO: "Verdura alargada y verde, fresca y crujiente.",
        PERA: "Fruta dulce con forma más ancha en la parte baja.",
        PERRO: "Animal doméstico que ladra.",
        PESCADO: "Alimento que se obtiene de peces u otros animales del agua.",
        PIE: "Parte del cuerpo que nos ayuda a sostenernos y caminar.",
        PIERNA: "Parte del cuerpo que va desde la cadera hasta el pie.",
        PINTOR: "Persona que pinta paredes, objetos o cuadros.",
        PIZARRA: "Superficie donde se escribe en clase.",
        PLANETA: "Astro que gira alrededor de una estrella.",
        PLATANO: "Fruta alargada y amarilla.",
        POLVORON: "Dulce de Navidad que se deshace en la boca.",
        PRIMAVERA: "Estación del año en la que florecen las plantas.",
        PRIMO: "El hijo de tu tío o de tu tía.",
        PROFESORA: "Mujer que enseña en una escuela o instituto.",
        PUERTA: "Pieza que abrimos para entrar o salir de un lugar.",
        QUESO: "Alimento que suele hacerse con leche.",
        RABIA: "Lo que sientes cuando algo te parece injusto.",
        RAYO: "Luz muy fuerte que cruza el cielo durante una tormenta.",
        REGALO: "Algo que damos a alguien para hacerle feliz.",
        REGLA: "Herramienta recta para medir o trazar líneas.",
        REYES: "Los tres Reyes Magos, que traen regalos el 6 de enero.",
        RODILLA: "Articulación que une el muslo con la parte de abajo de la pierna.",
        ROJO: "Color de la sangre o de muchas fresas.",
        ROSA: "Color suave parecido al de algunas flores.",
        SABADO: "Primer día del fin de semana.",
        SETA: "Sale en el bosque después de la lluvia; algunas se pueden comer.",
        SILLA: "Mueble para que se siente una persona.",
        SOFA: "Asiento blando y largo donde pueden sentarse varias personas.",
        SOL: "Estrella que da luz y calor a la Tierra.",
        SORPRESA: "Lo que sientes cuando pasa algo que no esperabas.",
        TEJON: "Animal de bosque, robusto y de patas cortas.",
        TENIS: "Deporte en el que se golpea una pelota con una raqueta por encima de una red.",
        TIA: "La hermana de tu madre o de tu padre.",
        TIGRE: "Gran felino con rayas oscuras.",
        TIJERAS: "Herramienta para cortar papel o tela.",
        TIO: "El hermano de tu madre o de tu padre.",
        TOMATE: "Fruto rojo que muchas veces se usa como verdura.",
        TORMENTA: "Tiempo con mucha lluvia, rayos y truenos.",
        TREN: "Vehículo formado por vagones que va por raíles.",
        TRISTEZA: "Lo que sientes cuando estás triste y tienes ganas de llorar.",
        TURRON: "Dulce de almendra o de chocolate típico de Navidad.",
        UVA: "Fruta pequeña que crece en racimos.",
        VACA: "Animal doméstico que da leche.",
        VELA: "Barra de cera con un hilo que da luz al encenderla.",
        VENTANA: "Abertura en la pared por donde entran la luz y el aire.",
        VENUS: "Planeta cercano a la Tierra.",
        VERANO: "La estación más calurosa del año.",
        VERDE: "Color de la hierba o de muchas hojas.",
        VERGUENZA: "Lo que sientes cuando te da apuro que los demás te miren.",
        VIENTO: "Aire que se mueve.",
        VIERNES: "Último día de la semana de colegio.",
        VILLANCICO: "Canción típica de Navidad.",
        ZANAHORIA: "Verdura alargada de color naranja.",
        ZAPATO: "Calzado que protege el pie al caminar.",
        ZORRO: "Animal del bosque parecido a un perro, normalmente rojizo.",
      }),
      ca: Object.freeze({
        ALEGRIA: "El que sents quan estàs content.",
        ALL: "Bulb blanc amb gust fort que es fa servir per cuinar.",
        ALUMNE: "Persona que aprèn a l'escola.",
        AMOR: "El que sents quan estimes molt algú.",
        ARBRE: "Planta gran amb tronc i branques; per Nadal en decorem un.",
        ARROS: "Gra petit i blanc que sovint es cuina bullit.",
        ATLETISME: "Esports de córrer, saltar i llançar.",
        AVI: "El pare de la teva mare o del teu pare.",
        AVIA: "La mare de la teva mare o del teu pare.",
        AVIO: "Vehicle que vola per l'aire.",
        BASQUET: "Esport en què s'ha de fer entrar la pilota per una cistella.",
        BICI: "Vehicle de dues rodes que es mou amb pedals.",
        BLANC: "Color de la neu o del paper.",
        BLAU: "Color del cel en un dia clar.",
        BOCA: "Part del cos amb què mengem i parlem.",
        BOIRA: "Núvol baix que no ens deixa veure lluny.",
        BOLET: "Surt al bosc després de la pluja; alguns es poden menjar.",
        BOMBER: "Persona que apaga incendis i ajuda en emergències.",
        BRAC: "Part del cos que va de l'espatlla a la mà.",
        BUFANDA: "Peça llarga que ens posem al voltant del coll quan fa fred.",
        BUS: "Vehicle gran que transporta passatgers.",
        CADIRA: "Moble per seure una persona.",
        CAGANER: "Figureta divertida que s'amaga al pessebre.",
        CALMA: "El que sents quan estàs tranquil i relaxat.",
        CALOR: "El que sentim quan la temperatura és alta.",
        CAMA: "Part del cos que va del maluc fins al peu.",
        CAMPANA: "Objecte de metall que sona quan el piquen.",
        CAP: "Part del cos on hi ha els ulls, el nas i la boca.",
        CARN: "Aliment que és la part tova del cos d'animals com la vaca o el pollastre.",
        CARTER: "Persona que reparteix cartes i paquets.",
        CASTANYA: "Fruit sec de color marró que es menja torrat a la tardor.",
        CASTANYERA: "Dona que ven castanyes torrades al carrer.",
        CAVALL: "Animal gran que pot córrer molt i portar persones.",
        CEBA: "Verdura rodona amb capes i gust fort.",
        CELEST: "Blau clar i suau.",
        CERVOL: "Animal de potes llargues que pot tenir banyes.",
        CICLISME: "Esport que es fa amb bicicleta.",
        CIRERA: "Fruita petita, rodona i sovint vermella.",
        CODONY: "Fruita groga i dura amb què es fa codonyat.",
        COET: "Vehicle que puja a l'espai.",
        COGOMBRE: "Verdura allargada i verda, fresca i cruixent.",
        COL: "Verdura de fulles ben juntes i forma rodona.",
        CONILL: "Animal petit amb orelles llargues.",
        COSI: "El fill del teu oncle o de la teva tia.",
        COTXE: "Vehicle de quatre rodes per anar per carretera.",
        CUINA: "Lloc de la casa on es prepara el menjar.",
        CUINER: "Persona que prepara el menjar.",
        DIJOUS: "Dia de la setmana que va després de dimecres.",
        DILLUNS: "Primer dia de la setmana.",
        DIMARTS: "Dia de la setmana que va després de dilluns.",
        DIMECRES: "Dia del mig de la setmana d'escola.",
        DISSABTE: "Primer dia del cap de setmana.",
        DIT: "Cadascuna de les parts llargues de la mà.",
        DIUMENGE: "Últim dia de la setmana.",
        DIVENDRES: "Últim dia de la setmana d'escola.",
        ELEFANT: "Animal molt gran amb trompa.",
        ENCIAM: "Verdura de fulles verdes que es menja en amanides.",
        ENYORANCA: "El que sents quan trobes a faltar algú o algun lloc.",
        ESPELMA: "Barra de cera amb un fil que fa llum quan s'encén.",
        ESQUENA: "Part del darrere del cos, del coll a la cintura.",
        ESQUIROL: "Animal petit que s'enfila als arbres i menja fruits secs.",
        ESTIU: "L'estació més calorosa de l'any.",
        ESTRELLA: "Astre que fa llum al cel.",
        FALDILLA: "Peça de roba que penja des de la cintura.",
        FASTIC: "El que sents davant d'una cosa bruta o que fa pudor.",
        FINESTRA: "Obertura a la paret per on entren la llum i l'aire.",
        FORMATGE: "Aliment que normalment es fa amb llet.",
        FORNER: "Persona que fa o ven pa.",
        FRED: "El que sentim quan la temperatura és baixa.",
        FULLA: "Part plana de les plantes que a la tardor es torna groga i cau.",
        FUTBOL: "Esport en què dos equips intenten marcar gols amb els peus.",
        GAT: "Animal domèstic que miola.",
        GENOLL: "Articulació que uneix la cuixa amb la part de baix de la cama.",
        GERMA: "Noi que té la mateixa mare o el mateix pare que tu.",
        GERMANA: "Noia que té la mateixa mare o el mateix pare que tu.",
        GIMNASTICA: "Esport amb salts, voltes i exercicis d'equilibri.",
        GIRAFA: "Animal molt alt amb el coll llarg.",
        GLA: "Fruit petit de l'alzina i del roure.",
        GOMA: "Objecte que serveix per esborrar llapis.",
        GORRA: "Barret amb visera per protegir-se del sol.",
        GOS: "Animal domèstic que lladra.",
        GRIS: "Color entre el blanc i el negre.",
        GROC: "Color del sol o d'una llimona.",
        GUANT: "Peça que cobreix la mà i cada dit.",
        GUINEU: "Animal del bosc semblant a un gos, sovint de color rogenc.",
        HABITACIO: "Lloc de la casa on dormim.",
        HANDBOL: "Esport en què dos equips marquen gols llançant la pilota amb la mà.",
        HIVERN: "L'estació més freda de l'any.",
        JAQUETA: "Peça d'abric que es corda per davant.",
        JERSEI: "Peça de roba de llana per anar abrigat.",
        KIWI: "Fruita petita amb pell marró i interior verd.",
        LAVABO: "Lloc de la casa on ens rentem.",
        LILA: "Color entre el blau i el rosa.",
        LLAMP: "Llum molt forta que travessa el cel durant una tempesta.",
        LLAPIS: "Eina per escriure o dibuixar.",
        LLEO: "Gran felí amb crinera.",
        LLET: "Líquid blanc que beuen les cries de molts mamífers.",
        LLIBRE: "Conjunt de pàgines per llegir o estudiar.",
        LLIT: "Moble on dormim.",
        LLOP: "Animal salvatge semblant a un gos.",
        LLUNA: "Satèl·lit que gira al voltant de la Terra.",
        MA: "Part del cos amb dits per agafar coses.",
        MADUIXA: "Fruita vermella petita amb llavors per fora.",
        MAGRANA: "Fruita de tardor plena de grans vermells i sucosos.",
        MARE: "Dona que té fills o filles i en té cura.",
        MARRO: "Color de la fusta o de la xocolata.",
        MART: "Planeta rogenc del sistema solar.",
        MELO: "Fruita gran, rodona i refrescant.",
        MENJADOR: "Lloc de la casa on mengem.",
        MESTRA: "Dona que ensenya a l'escola.",
        METGE: "Persona que cuida la salut i tracta malalties.",
        METRO: "Tren urbà que circula per la ciutat, sovint sota terra.",
        MITJO: "Peça de roba que cobreix el peu dins la sabata.",
        MONIATO: "Tubercle dolç que es menja al forn per la Castanyada.",
        MOTO: "Vehicle de dues rodes amb motor.",
        MOTXILLA: "Bossa amb tirants que es porta a l'esquena.",
        MUSSOL: "Ocell nocturn amb ulls grossos.",
        NADO: "Criatura que fa poc que ha nascut.",
        NAS: "Part del cos amb què olorem i respirem.",
        NATACIO: "Esport que es fa nedant a l'aigua.",
        NEGRE: "Color de la nit sense llum.",
        NEU: "Aigua gelada que cau del cel en flocs blancs.",
        NEULES: "Galetes primes i enrotllades que es mengen per Nadal.",
        NUVOL: "Massa blanca o grisa que sura al cel.",
        ONCLE: "El germà de la teva mare o del teu pare.",
        ORBITA: "Camí que fa un astre al voltant d'un altre.",
        ORELLA: "Part del cos amb què sentim.",
        OS: "Animal gran i fort del bosc.",
        OU: "Aliment amb closca que ponen aus com la gallina.",
        OVELLA: "Animal domèstic que dona llana.",
        PA: "Aliment fet amb farina i fornejat.",
        PAGES: "Persona que treballa la terra o cuida animals de granja.",
        PANELLET: "Dolç petit d'ametlla típic de la Castanyada.",
        PANTALONS: "Peça de roba que tapa cada cama per separat.",
        PARAIGUA: "Objecte que obrim damunt del cap perquè la pluja no ens mulli.",
        PARE: "Home que té fills o filles i en té cura.",
        PASTA: "Aliment fet amb farina que es cou amb aigua.",
        PASTANAGA: "Verdura allargada de color taronja.",
        PATATA: "Verdura que creix sota terra; es menja fregida, bullida o al forn.",
        PATINATGE: "Esport que es fa amb patins.",
        PEIX: "Animal que viu a l'aigua i respira per brànquies; també en mengem.",
        PERA: "Fruita dolça amb la part de sota més ampla.",
        PESSEBRE: "Escena de figuretes que es munta per Nadal.",
        PEU: "Part del cos que ens ajuda a sostenir-nos i caminar.",
        PILOTA: "Objecte rodó per jugar a molts esports.",
        PINTOR: "Persona que pinta parets, objectes o quadres.",
        PISSARRA: "Superfície on s'escriu a classe.",
        PLANETA: "Astre que gira al voltant d'una estrella.",
        PLATAN: "Fruita allargada i groga.",
        PLUJA: "Aigua que cau dels núvols.",
        POMA: "Fruita rodona que pot ser vermella, verda o groga.",
        POR: "El que sents quan creus que et pot passar alguna cosa dolenta.",
        PORTA: "Peça que obrim per entrar o sortir d'un lloc.",
        PRIMAVERA: "Estació de l'any en què floreixen les plantes.",
        PROFESSORA: "Dona que ensenya en una escola o institut.",
        QUADERN: "Llibret de fulls per escriure o dibuixar.",
        RABIA: "El que sents quan una cosa et sembla injusta.",
        RAIM: "Conjunt de grans petits de fruita que pengen junts.",
        REGAL: "Cosa que donem a algú per fer-lo content.",
        REGLE: "Eina recta per mesurar o dibuixar línies.",
        ROSA: "Color suau semblant al d'algunes flors.",
        SABATA: "Calçat que protegeix el peu quan caminem.",
        SAMARRETA: "Peça de roba lleugera per a la part de dalt del cos.",
        SOFA: "Seient tou i llarg on poden seure diverses persones.",
        SOL: "Estrella que dona llum i calor a la Terra.",
        SORPRESA: "El que sents quan passa una cosa que no esperaves.",
        TARDOR: "Estació de l'any en què cauen les fulles dels arbres.",
        TARONJA: "Fruita rodona i sucosa; el seu color també es diu taronja.",
        TAULA: "Moble amb una superfície plana on mengem o treballem.",
        TEIXO: "Animal de bosc, robust i de potes curtes.",
        TEMPESTA: "Temps amb molta pluja, llamps i trons.",
        TENNIS: "Esport en què es colpeja una pilota amb una raqueta per sobre d'una xarxa.",
        TIA: "La germana de la teva mare o del teu pare.",
        TIGRE: "Gran felí amb ratlles fosques.",
        TIO: "Tronc que, per Nadal, fem cagar perquè ens porti regals.",
        TISORES: "Eina per tallar paper o roba.",
        TOMAQUET: "Fruit vermell que moltes vegades fem servir com una verdura.",
        TORRO: "Dolç d'ametlla o de xocolata típic de Nadal.",
        TREN: "Vehicle format per vagons que va per vies.",
        TRISTESA: "El que sents quan estàs trist i tens ganes de plorar.",
        ULL: "Part del cos amb què veiem.",
        VACA: "Animal domèstic que dona llet.",
        VAIXELL: "Vehicle que navega per l'aigua.",
        VENT: "Aire que es mou.",
        VENUS: "Planeta proper a la Terra.",
        VERD: "Color de l'herba o de moltes fulles.",
        VERGONYA: "El que sents quan et fa cosa que els altres et mirin.",
        VERMELL: "Color de la sang o de moltes maduixes.",
        ZEBRA: "Animal semblant al cavall amb ratlles blanques i negres.",
      }),
      en: Object.freeze({
        ACORN: "The small nut of an oak tree.",
        ANGRY: "How you feel when something seems unfair.",
        APPLE: "A round fruit that can be red, green, or yellow.",
        ARM: "The body part that goes from the shoulder to the hand.",
        AUNT: "The sister of your mum or dad.",
        AUTUMN: "The season when leaves fall from the trees.",
        BABY: "A very young child.",
        BACK: "The part of your body behind you, from your neck to your waist.",
        BACKPACK: "A bag with straps that is carried on the back.",
        BADGER: "A wild animal with short legs and a black-and-white striped face that digs burrows.",
        BAKER: "A person who makes or sells bread.",
        BALL: "A round object used to play many games.",
        BANANA: "A long yellow fruit.",
        BASKETBALL: "A game where players throw a ball through a high hoop.",
        BATHROOM: "The room where you wash.",
        BEAR: "A large, strong wild animal.",
        BED: "The furniture you sleep on.",
        BEDROOM: "The room where you sleep.",
        BELL: "A metal object that rings when you hit it.",
        BIKE: "A two-wheeled vehicle moved with pedals.",
        BLACK: "The colour of a night with no light.",
        BLUE: "The colour of the sky on a clear day.",
        BOARD: "A surface used for writing in class.",
        BOAT: "A vehicle that travels on water.",
        BOOK: "A set of pages for reading or studying.",
        BORED: "How you feel when you have nothing interesting to do.",
        BREAD: "Food made from flour and baked.",
        BROTHER: "A boy or man who has the same parents as you.",
        BROWN: "The colour of wood or chocolate.",
        BUS: "A large vehicle that carries passengers.",
        CABBAGE: "A round vegetable with tightly packed leaves.",
        CALM: "How you feel when you are quiet and relaxed.",
        CANDLE: "A stick of wax with a string that gives light when you light it.",
        CAP: "A soft hat with a peak that keeps the sun out of your eyes.",
        CAR: "A four-wheeled vehicle for roads.",
        CAROL: "A song that people sing at Christmas.",
        CARROT: "A long orange vegetable.",
        CAT: "A pet animal that meows.",
        CHAIR: "A seat for one person.",
        CHEESE: "Food that is usually made from milk.",
        CHERRY: "A small round fruit that is often red.",
        CHESTNUT: "A shiny brown nut that people roast and eat in autumn.",
        CLOUD: "A white or grey mass floating in the sky.",
        COLD: "How it feels when the temperature is low.",
        COOK: "A person who prepares food.",
        COUSIN: "The child of your aunt or uncle.",
        COW: "A farm animal that gives milk.",
        CUCUMBER: "A long green vegetable that is fresh and crunchy.",
        CYAN: "A bright greenish-blue colour.",
        CYCLING: "Riding a bike as a sport.",
        DEER: "An animal with long legs that may have antlers.",
        DOCTOR: "A person who cares for health and treats illnesses.",
        DOG: "A pet animal that barks.",
        DOOR: "You open it to go in or out of a room.",
        EAR: "The body part used for hearing.",
        EGG: "Food with a shell that birds such as hens lay.",
        ELEPHANT: "A very large animal with a trunk.",
        ERASER: "An object used to rub out pencil marks.",
        EXCITED: "How you feel when you are really looking forward to something.",
        EYE: "The body part used for seeing.",
        FARMER: "A person who works the land or looks after farm animals.",
        FATHER: "A man who has children and looks after them.",
        FINGER: "One of the long parts of the hand.",
        FIREFIGHTER: "A person who puts out fires and helps in emergencies.",
        FISH: "An animal that lives in water and breathes through gills; we also eat it.",
        FOG: "A low cloud that stops you seeing far.",
        FOOT: "The body part that helps us stand and walk.",
        FOOTBALL: "A game where two teams try to kick a ball into a goal.",
        FOX: "A wild animal like a dog, often with reddish fur.",
        FRIDAY: "The last day of the school week.",
        GARDEN: "The land next to a house where plants grow.",
        GARLIC: "A white bulb with a strong taste used in cooking.",
        GIRAFFE: "A very tall animal with a long neck.",
        GLOVE: "Something you wear on your hand, with a place for each finger.",
        GRANDMA: "The mother of your mum or dad.",
        GRANDPA: "The father of your mum or dad.",
        GRAPE: "A small fruit that grows in bunches.",
        GREEN: "The colour of grass or many leaves.",
        GREY: "A colour between black and white.",
        GYMNASTICS: "A sport with jumps, rolls and balancing.",
        HAND: "The body part with fingers for holding things.",
        HANDBALL: "A team game where players throw a ball into a goal.",
        HAPPY: "How you feel when something good happens.",
        HARVEST: "The time when farmers pick their crops.",
        HEAD: "The body part where the eyes, nose, and mouth are.",
        HEDGEHOG: "A small animal covered in spines that sleeps through the winter.",
        HORSE: "A large animal that can run fast and carry people.",
        HOT: "How it feels when the temperature is high.",
        JACKET: "A short coat that you wear outside.",
        JUMPER: "A warm woolly top.",
        KITCHEN: "The room where food is cooked.",
        KIWI: "A small fruit with brown skin and green inside.",
        KNEE: "The joint between the thigh and the lower leg.",
        LEAF: "A flat part of a plant that turns yellow and falls in autumn.",
        LEG: "The body part that goes from the hip to the foot.",
        LETTUCE: "A leafy green vegetable often used in salads.",
        LIGHTNING: "A very bright flash of light in the sky during a storm.",
        LION: "A big cat with a mane.",
        MARS: "The reddish planet in the solar system.",
        MEAT: "Food that is the soft part of animals such as cows or chickens.",
        MELON: "A large, round, refreshing fruit.",
        METRO: "A city train that often travels underground.",
        MILK: "A white liquid that young mammals drink.",
        MONDAY: "The first day of the week.",
        MOON: "The natural satellite that goes around Earth.",
        MOTHER: "A woman who has children and looks after them.",
        MOTORBIKE: "A two-wheeled vehicle with an engine.",
        MOUTH: "The body part used for eating and speaking.",
        MUSHROOM: "It grows in the woods after rain; some kinds are good to eat.",
        NOSE: "The body part used for smelling and breathing.",
        NOTEBOOK: "A set of blank pages joined together for writing or drawing.",
        ONION: "A round vegetable with layers and a strong taste.",
        ORANGE: "A round, juicy fruit; its colour is also called orange.",
        ORBIT: "The path one object follows around another in space.",
        OWL: "A night bird with large eyes.",
        PAINTER: "A person who paints walls, objects, or pictures.",
        PASTA: "Food made from flour that is cooked in water.",
        PEAR: "A sweet fruit that is wider at the bottom.",
        PENCIL: "A tool used for writing or drawing.",
        PINK: "A soft colour like some flowers.",
        PLANE: "A vehicle that flies through the air.",
        PLANET: "A space object that moves around a star.",
        POSTMAN: "A person who delivers letters and parcels.",
        POTATO: "A vegetable that grows underground; we eat it fried, boiled or baked.",
        PRESENT: "Something you give to someone to make them happy.",
        PUDDLE: "A small pool of rainwater on the ground.",
        PUMPKIN: "A big round orange vegetable that grows on the ground.",
        PURPLE: "A colour between blue and red.",
        RABBIT: "A small animal with long ears.",
        RAIN: "Water that falls from the clouds.",
        RAINCOAT: "A coat that keeps you dry when it rains.",
        RED: "The colour of blood or many strawberries.",
        REINDEER: "A deer with big antlers that lives in cold places.",
        RICE: "A small white grain that is often boiled.",
        ROCKET: "A vehicle that travels into space.",
        RULER: "A straight tool for measuring or drawing lines.",
        RUNNING: "Moving fast on your feet.",
        SAD: "How you feel when you want to cry.",
        SATURDAY: "The first day of the weekend.",
        SCARED: "How you feel when you think something bad might happen.",
        SCARF: "A long piece of cloth you wear around your neck when it is cold.",
        SCISSORS: "A tool used to cut paper or fabric.",
        SHEEP: "A farm animal that gives wool.",
        SHIRT: "Clothing for the top half of your body, often with buttons.",
        SHOE: "Something you wear on your foot to walk outside.",
        SHY: "How you feel when you are nervous with people you do not know.",
        SISTER: "A girl or woman who has the same parents as you.",
        SKATING: "Moving on skates over ice or the ground.",
        SKIRT: "Clothing that hangs down from the waist.",
        SLEIGH: "A vehicle that slides over the snow.",
        SNOW: "Frozen water that falls from the sky in white flakes.",
        SNOWMAN: "A figure that people build out of snow.",
        SOCK: "Something soft you wear on your foot inside a shoe.",
        SOFA: "A long soft seat for several people.",
        SPRING: "The season when flowers start to grow.",
        SQUIRREL: "A small animal that climbs trees and eats nuts.",
        STAR: "A space object that shines with its own light.",
        STOCKING: "A big sock hung up at Christmas to be filled with presents.",
        STORM: "Weather with strong wind, heavy rain and often thunder.",
        STRAWBERRY: "A small red fruit with seeds on the outside.",
        STUDENT: "A person who learns at school.",
        SUMMER: "The hottest season of the year.",
        SUN: "The star that gives Earth light and heat.",
        SUNDAY: "The last day of the week.",
        SURPRISED: "How you feel when something you did not expect happens.",
        SWIMMING: "Moving through water using your arms and legs.",
        TABLE: "Furniture with a flat top where you eat or work.",
        TEACHER: "A person who teaches at school.",
        TENNIS: "A game where players hit a ball over a net with rackets.",
        THURSDAY: "The day of the week after Wednesday.",
        TIGER: "A big cat with dark stripes.",
        TIRED: "How you feel when you need to rest or sleep.",
        TOMATO: "A red fruit that is often used like a vegetable.",
        TRAIN: "A vehicle made of carriages that runs on tracks.",
        TREE: "A tall plant with a trunk and branches; at Christmas we decorate one.",
        TROUSERS: "Clothing that covers each leg separately.",
        TUESDAY: "The day of the week after Monday.",
        UMBRELLA: "Something you open over your head to stay dry in the rain.",
        UNCLE: "The brother of your mum or dad.",
        VENUS: "A planet close to Earth.",
        WEDNESDAY: "The day in the middle of the school week.",
        WHITE: "The colour of snow or paper.",
        WIND: "Air that moves.",
        WINDOW: "An opening in the wall that lets in light and air.",
        WINTER: "The coldest season of the year.",
        WOLF: "A wild animal like a dog.",
        YELLOW: "The colour of the sun or a ripe banana.",
        ZEBRA: "An animal like a horse with black and white stripes.",
      }),
    }),
    samplePuzzles: Object.freeze({
      es: Object.freeze([
        Object.freeze({
          title: "Primeros pasos: animales",
          difficulty: "easy",
          size: "8",
          timerDuration: 0,
          hintsAllowed: -1,
          words: ["perro", "gato", "oso", "vaca", "lobo", "león"].join("\n"),
        }),
        Object.freeze({
          title: "Animales del bosque",
          difficulty: "easy",
          size: "auto",
          words: ["ardilla", "zorro", "ciervo", "tejón", "búho", "lobo", "conejo", "oso"].join("\n"),
        }),
        Object.freeze({
          title: "Alimentos saludables",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "col", "naranja", "pera", "tomate", "arroz", "leche"].join("\n"),
        }),
        Object.freeze({
          title: "Frutas del mercado",
          difficulty: "easy",
          size: "auto",
          words: ["manzana", "pera", "plátano", "naranja", "kiwi", "melón", "uva", "cereza"].join("\n"),
        }),
        Object.freeze({
          title: "Verduras del huerto",
          difficulty: "easy",
          size: "auto",
          words: ["zanahoria", "patata", "cebolla", "col", "lechuga", "tomate", "pepino", "ajo"].join("\n"),
        }),
        Object.freeze({
          title: "Transportes de la ciudad",
          difficulty: "easy",
          size: "auto",
          words: ["coche", "tren", "barco", "avión", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficios del barrio",
          difficulty: "medium",
          size: "auto",
          words: ["maestra", "médico", "cocinero", "pintor", "bombero", "panadero", "granjero", "cartero"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "órbita", "marte", "venus", "luna", "cohete", "estrella"].join("\n"),
        }),
      ]),
      ca: Object.freeze([
        Object.freeze({
          title: "Primers passos: animals",
          difficulty: "easy",
          size: "8",
          timerDuration: 0,
          hintsAllowed: -1,
          words: ["gos", "gat", "conill", "vaca", "llop", "lleó"].join("\n"),
        }),
        Object.freeze({
          title: "Animals del bosc",
          difficulty: "easy",
          size: "auto",
          words: ["esquirol", "guineu", "cérvol", "teixó", "mussol", "llop", "conill", "os"].join("\n"),
        }),
        Object.freeze({
          title: "Aliments saludables",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "col", "taronja", "pera", "tomàquet", "arròs", "llet"].join("\n"),
        }),
        Object.freeze({
          title: "Fruites del mercat",
          difficulty: "easy",
          size: "auto",
          words: ["poma", "pera", "plàtan", "taronja", "kiwi", "meló", "raïm", "cirera"].join("\n"),
        }),
        Object.freeze({
          title: "Verdures de l'hort",
          difficulty: "easy",
          size: "auto",
          words: ["pastanaga", "patata", "ceba", "col", "enciam", "tomàquet", "cogombre", "all"].join("\n"),
        }),
        Object.freeze({
          title: "Transports de la ciutat",
          difficulty: "easy",
          size: "auto",
          words: ["cotxe", "tren", "vaixell", "avió", "bici", "moto", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Oficis del barri",
          difficulty: "medium",
          size: "auto",
          words: ["mestra", "metge", "cuiner", "pintor", "bomber", "forner", "pagès", "carter"].join("\n"),
        }),
        Object.freeze({
          title: "Sistema solar",
          difficulty: "medium",
          size: "auto",
          words: ["sol", "planeta", "òrbita", "mart", "venus", "lluna", "coet", "estrella"].join("\n"),
        }),
      ]),
      en: Object.freeze([
        Object.freeze({
          title: "First steps: animals",
          difficulty: "easy",
          size: "8",
          timerDuration: 0,
          hintsAllowed: -1,
          words: ["dog", "cat", "bear", "cow", "wolf", "lion"].join("\n"),
        }),
        Object.freeze({
          title: "Forest animals",
          difficulty: "easy",
          size: "auto",
          words: ["squirrel", "fox", "deer", "badger", "owl", "wolf", "rabbit", "bear"].join("\n"),
        }),
        Object.freeze({
          title: "Healthy food",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "cabbage", "orange", "pear", "tomato", "rice", "milk"].join("\n"),
        }),
        Object.freeze({
          title: "Market fruits",
          difficulty: "easy",
          size: "auto",
          words: ["apple", "pear", "banana", "orange", "kiwi", "melon", "grape", "cherry"].join("\n"),
        }),
        Object.freeze({
          title: "Garden vegetables",
          difficulty: "easy",
          size: "auto",
          words: ["carrot", "potato", "onion", "cabbage", "lettuce", "tomato", "cucumber", "garlic"].join("\n"),
        }),
        Object.freeze({
          title: "City transport",
          difficulty: "easy",
          size: "auto",
          words: ["car", "train", "boat", "plane", "bike", "bus", "metro"].join("\n"),
        }),
        Object.freeze({
          title: "Neighbourhood jobs",
          difficulty: "medium",
          size: "auto",
          words: ["teacher", "doctor", "cook", "painter", "firefighter", "baker", "farmer", "postman"].join("\n"),
        }),
        Object.freeze({
          title: "Solar system",
          difficulty: "medium",
          size: "auto",
          words: ["sun", "planet", "orbit", "mars", "venus", "moon", "rocket", "star"].join("\n"),
        }),
      ]),
    }),
  });
})(typeof window !== "undefined" ? window : globalThis);
